In [1]:
print("halo")

halo


In [2]:
import numpy as np
import networkx as nx
from pprint import pprint

In [3]:
g = nx.Graph([
    (1,2), (1,5), (1,8),
    (2,3), (2,6),
    (3,4),
    (4,5),
    (6,7),
    (7,8)
])
A = nx.to_numpy_array(g)
A

array([[0., 1., 1., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 1., 1., 0., 0.],
       [1., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 1., 0., 0.]])

In [4]:
eigval, eigvec = np.linalg.eigh(A)
eigval

array([-2.00000000e+00, -1.81360650e+00, -1.41421356e+00, -3.73351794e-16,
        4.70683420e-01,  1.00000000e+00,  1.41421356e+00,  2.34292308e+00])

In [5]:
eigvec

array([[-5.77350269e-01,  2.60554635e-01,  5.70304319e-17,
         4.39346461e-18,  4.55984803e-01, -4.08248290e-01,
        -1.51928065e-18, -4.73486158e-01],
       [ 5.77350269e-01,  2.60554635e-01,  1.33901143e-16,
        -3.14328158e-18,  4.55984803e-01,  4.08248290e-01,
         4.52452909e-17, -4.73486158e-01],
       [ 2.88675135e-01, -3.66549107e-01,  3.53553391e-01,
         5.00000000e-01, -1.20680158e-01, -4.08248290e-01,
        -3.53553391e-01, -3.17927746e-01],
       [ 2.88675135e-01, -3.66549107e-01, -3.53553391e-01,
        -5.00000000e-01, -1.20680158e-01, -4.08248290e-01,
         3.53553391e-01, -3.17927746e-01],
       [-2.88675135e-01, -3.66549107e-01,  3.53553391e-01,
        -5.00000000e-01, -1.20680158e-01,  4.08248290e-01,
        -3.53553391e-01, -3.17927746e-01],
       [-2.88675135e-01, -3.66549107e-01, -3.53553391e-01,
         5.00000000e-01, -1.20680158e-01,  4.08248290e-01,
         3.53553391e-01, -3.17927746e-01],
       [ 5.27355937e-16,  4.042212

In [6]:
print(type(eigval), type(eigvec))

<class 'numpy.ndarray'> <class 'numpy.ndarray'>
